/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.coolspy3.calccalcs;

import javax.swing.SwingUtilities;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(GUI::new);
    }
}
